// question-metrics-ts/src/Login.tsx
import * as React from 'react';
import './App.css';

export class Login extends React.Component {
    
    constructor(props: any) {
        super(props);

    }

    public render() {
      return (        
        <div className="container">
            <div className="login-container">
                    <div id="output">&nbsp</div>
                    <div className="avatar" />
                    <p className="appName">Question Metrics</p>
                    <div className="form-box">
                        <form action="" method="">
                            <input name="user" type="text" placeholder="username" />
                            <input type="password" placeholder="password" />
                            <button className="btn btn-info btn-block login" type="button">Login</button>
                        </form>
                    </div>
                </div>
                
        </div>
      )
    }
}

// question-metrics-ng/question-metrics/src/app/user/login.component.ts
import { Component } from '@angular/core';

@Component({
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  title = 'question-metrics Login';
}

<h1>Login Page</h1>

<div className="container">
    <div className="login-container">
            <div id="output">&nbsp</div>
            <div className="avatar"></div>
            <p className="appName">Question Metrics</p>
            <div className="form-box">
                <form action="" method="">
                    <input name="user" type="text" placeholder="username" />
                    <input type="password" placeholder="password" />
                    <button className="btn btn-info btn-block login" type="button">Login</button>
                </form>
            </div>
        </div>
        
</div>
